<?xml version="1.0" encoding="UTF-8"?>
<!--引入外部dtd-->
 <!DOCTYPE students SYSTEM "student.dtd">

<!--&lt;!&ndash;内部dtd,了解，不使用这种法式&ndash;&gt;-->
<!--<!DOCTYPE students [-->
<!--  <!ELEMENT students (student+)>   &lt;!&ndash;通过ELEMENT定义标签:students，(student*)：students下放子标签，可以出现*次&ndash;&gt;-->
<!--  <!ELEMENT student (name,age,sex)>   &lt;!&ndash;又定义了student标签，有：(name,age,sex)：声明student标签，按顺序依次用name，gage，sex子标签(且出现一次)&ndash;&gt;-->
<!--  <!ELEMENT name (#PCDATA)>   &lt;!&ndash;声明name标签，它的标签体内是：(#PCDATA)：字符串类型&ndash;&gt;-->
<!--  <!ELEMENT age (#PCDATA)>-->
<!--  <!ELEMENT sex (#PCDATA)>-->
<!--  <!ATTLIST student number ID #REQUIRED>  &lt;!&ndash;通过ATTLIST定义属性，定义stedent的属性，属性名number；属性类型：ID，属性名唯一；#REQUIRED：number属性必须出现&ndash;&gt;-->

<!--  ]>-->
<students>
  <student number="s001">
    <name>zhangsan</name>
    <age>23</age>
    <sex>male</sex>
  </student>
  <student number="s002">
    <name>lisi</name>
    <age>24</age>
    <sex>female</sex>
  </student>
</students>
